module Assimp

  Components = bitmask(:components, [
    :NORMALS, 1,
    :TANGENTS_AND_BITANGENTS,
    :COLORS,
    :TEXCOORDS,
    :BONEWEIGHTS,
    :ANIMATIONS,
    :TEXTURES,
    :LIGHTS,
    :CAMERAS,
    :MESHES,
    :MATERIALS,
    :COLORS0, 20,
    :COLORS1,
    :COLORS2,
    :COLORS3,
    :COLORS4,
    :TEXCOORDS0, 25,
    :TEXCOORDS1,
    :TEXCOORDS2,
    :TEXCOORDS3,
    :TEXCOORDS4,
    :TEXCOORDS5,
    :TEXCOORDS6,
  ])

  UVTRAFO_SCALING = 0x1
  UVTRAFO_ROTATION = 0x2
  UVTRAFO_TRANSLATION = 0x4
  UVTRAFO_ALL = UVTRAFO_SCALING | UVTRAFO_ROTATION | UVTRAFO_TRANSLATION

end
